import {Inter, Rubik} from 'next/font/google'
import './globals.css'
import Header from "@/app/components/Header";

const rubik = Rubik({subsets: ['latin']})

export const metadata = {
    title: 'Blog-vježba',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={rubik.className}>
        <Header/>
        <main>
            {children}
        </main>
        </body>
        </html>
    )
}
